### ISSUE TITLE
Add new Sorting algorithms

### ISSUE THREAD

**Issue by AryanSahoo-2003** [anirudhlakhotia/visual-sorting-algorithms#30]
i want to add new linear sorting algorithms like bucket,radix sort and wanted to show why even though Radix sort has a better time complexity, why is it that quick sort preferred both in APIs by writing comments on it

**Comment by anirudhlakhotia** [comment]
Hey @AryanSahoo-2003 
Please check out #26 :)
This is a duplicate issue for the same and I'll be closing it for that reason

**Comment by AryanSahoo-2003** [comment]
ohk sir ..I did'nt saw that
